name: Bug Report
description: Create a report to fix issues
title: "[BUG][PLATFORM][DEVICE][SailfishOS-Version]: "
labels: ["BUG", "TRIAGE"]
body:
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please describe the software environment you have on the device.
        Write any if a value doesn't apply, e.g. affects all devices.
        Examples:
        - **Platform:** lena
        - **Device:** pdx213 xqbt52 (Xperia 10 III)
        - **Sailfish OS Version:** Sailfish OS 4.3 Suomenlinna
        - **Kernel version:** 4.19.188-gc7505f2d6045-dirty
        - **Droid-Hal Version:** 0.6
        - **Droid-System Version:** 0.1
        - **Software binaries version:** SW_binaries_for_Xperia_Android_11_4.19_v8a_lena.img

        *Please also replace the placeholders with those values in the title!*
      value: |
        - **Platform:**
        - **Device:**
        - **Sailfish OS Version:**
        - **Kernel version:**
        - **Droid-Hal Version:**
        - **Droid-System Version:**
        - **Software binaries version:**
      render: markdown
    validations:
      required: true
  - type: textarea
    id: previously-working-on
    attributes:
      label: Previously working on
      description: |
        Has this always been a problem, or is it a new issue?
        Please be specific. Include things like:
        - previous sync and build date
        - latest known working kernel version including commit id and
        - any other information that may be relevant

      render: markdown
    validations:
      required: true
  - type: textarea
    id: description-bug
    attributes:
      label: Description
      description: |
        Write the issue description here.
    validations:
      required: true
  - type: textarea
    id: symptoms
    attributes:
      label: Symptoms
      description: |
        Write the symptoms here.
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce the bug
      description: |
        Please describe how exactly reproduce the issue step by step.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context, e.g. upload logs or screenshots about the bug here.
        It will be very hard for us to track down your issue without logs, so
        please attach a logcat and dmesg for us here!
