name: Feature Request
description: Suggest an idea for this project
title: "[REQUEST][PLATFORM][SailfishOS-Version]: "
labels: ["REQUEST", "TRIAGE"]
body:
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please describe the software environment you have on the device.
        Write any if a value doesn't apply.
        Examples:
        - **Platform:** lena
        - **Device:** pdx213 xqbt52 (Xperia 10 III)

        *Please also replace the placeholders with those values in the title!*
      value: |
        - **Platform:**
        - **Device:**
      render: markdown
    validations:
      required: true
  - type: textarea
    id: describe-feature-request
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
       A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
